data0 <- read.table("data0.txt", header = TRUE, sep = " ")
png("Plot0.png")
plot(data0$Collision, data0$Energy, type = "l")
dev.off()
png("Plot_log0.png")
plot(data0$Collision, data0$Energy, type = "l", log = 'x')
dev.off()

data1 <- read.table("data1.txt", header = TRUE, sep = " ")
png("Plot1.png")
plot(data1$Collision, data1$Energy, type = "l")
dev.off()
png("Plot_log1.png")
plot(data1$Collision, data1$Energy, type = "l", log = 'x')
dev.off()

data2 <- read.table("data2.txt", header = TRUE, sep = " ")
png("Plot2.png")
plot(data2$Collision, data2$Energy, type = "l")
dev.off()
png("Plot_log2.png")
plot(data2$Collision, data2$Energy, type = "l", log = 'x')
dev.off()

data3 <- read.table("data3.txt", header = TRUE, sep = " ")
png("Plot3.png")
plot(data3$Collision, data3$Energy, type = "l")
dev.off()
png("Plot_log3.png")
plot(data3$Collision, data3$Energy, type = "l", log = 'x')
dev.off()

data4 <- read.table("data4.txt", header = TRUE, sep = " ")
png("Plot4.png")
plot(data4$Collision, data4$Energy, type = "l")
dev.off()
png("Plot_log4.png")
plot(data4$Collision, data4$Energy, type = "l", log = 'x')
dev.off()

data5 <- read.table("data5.txt", header = TRUE, sep = " ")
png("Plot5.png")
plot(data5$Collision, data5$Energy, type = "l")
dev.off()
png("Plot_log5.png")
plot(data5$Collision, data5$Energy, type = "l", log = 'x')
dev.off()

data6 <- read.table("data6.txt", header = TRUE, sep = " ")
png("Plot6.png")
plot(data6$Collision, data6$Energy, type = "l")
dev.off()
png("Plot_log6.png")
plot(data6$Collision, data6$Energy, type = "l", log = 'x')
dev.off()

data7 <- read.table("data7.txt", header = TRUE, sep = " ")
png("Plot7.png")
plot(data7$Collision, data7$Energy, type = "l")
dev.off()
png("Plot_log7.png")
plot(data7$Collision, data7$Energy, type = "l", log = 'x')
dev.off()

data8 <- read.table("data8.txt", header = TRUE, sep = " ")
png("Plot8.png")
plot(data8$Collision, data8$Energy, type = "l")
dev.off()
png("Plot_log8.png")
plot(data8$Collision, data8$Energy, type = "l", log = 'x')
dev.off()

data9 <- read.table("data9.txt", header = TRUE, sep = " ")
png("Plot9.png")
plot(data9$Collision, data9$Energy, type = "l")
dev.off()
png("Plot_log9.png")
plot(data9$Collision, data9$Energy, type = "l", log = 'x')
dev.off()